[env:sparkfun_thingplusrp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = sparkfun_thingplusrp2040
framework = arduino
board_build.core = earlephilhower

lib_deps =
    sparkfun/SparkFun u-blox GNSS Arduino Library@^2.2.29
    huskylens/HuskyLens @ ^1.0.0
    sparkfun/SparkFun BMI270 Arduino Library @ ^1.0.3